version: "3"
services:
  stock-service:
    image: stock-service
    networks:
      - stock-mysql
    ports:
      - "8080:8080"  
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - stock-mysql
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  stock-mysql: