version: "3"
services:
  stock-service:
    image: stock-service
    ports:
      - "8080:8080"
    networks:
      - stock-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - stock-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  stock-mysql: