INSERT IGNORE INTO STOCKS (CUSIP_ID, NAME, TICKER, CURRENT_PRICE, LAST_UPDATED_TM) VALUES ('037833100', 'Apple Inc', 'AAPL', 130.06, current_timestamp());
INSERT IGNORE INTO STOCKS (CUSIP_ID, NAME, TICKER, CURRENT_PRICE, LAST_UPDATED_TM) VALUES ('594918104', 'Microsoft Corporation', 'MSFT', 244.72, current_timestamp());
INSERT IGNORE INTO STOCKS (CUSIP_ID, NAME, TICKER, CURRENT_PRICE, LAST_UPDATED_TM) VALUES ('02079K305', 'Alphabet Inc', 'GOOG', 2132.50, current_timestamp());
INSERT IGNORE INTO STOCKS (CUSIP_ID, NAME, TICKER, CURRENT_PRICE, LAST_UPDATED_TM) VALUES ('0231351066', 'Amazon.com', 'AMZN', 103.60, current_timestamp());
COMMIT;