CREATE TABLE IF NOT EXISTS STOCKS (
    CUSIP_ID VARCHAR(15) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    TICKER VARCHAR(10) NOT NULL, 
    CURRENT_PRICE DECIMAL, 
    LAST_UPDATED_TM DATETIME,
    CONSTRAINT PK_STOCKS PRIMARY KEY (CUSIP_ID) 
);
